# Generated by Django 6.0.3 on 2026-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
